version: 0.0
os: linux
files:
  - source: demo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/server/
    overwrite: true

hooks:
  BeforeInstall:
    - location: stop.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: install.sh
      timeout: 300
      runas: root
    - location: rename.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: validate.sh
      timeout: 300
      runas: root
